filmapp/urls.py
from django.urls import path
from . import views


urlpatterns = [

    path('', views.home, name='home'),
    path('admin_posts/', views.admin_posts, name='admin_posts'),
    path('guest/', views.guest_posts, name='guest'),
    path('create/', views.create_blog, name='create_blog'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_user, name='logout_user'),
    path('blog/<int:pk>/', views.blog_details, name='blog_details'),
    path('author/<int:author_id>/', views.author_posts, name='author_posts'),
    path('contact/', views.contact, name='contact'),
    path('search/', views.search, name='search'),
    path('blog/<int:pk>/', views.blog_details, name='blog_details'),
    path('blog/<int:pk>/comment/', views.add_comment, name='add_comment'),
    path('blog/<int:pk>/edit/', views.edit_blog, name='edit_blog'),
    path('blog/<pk>/delete/', views.delete_blog, name='delete_blog'),    
]

filmshift/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('filmapp.urls', 'filmapp'), namespace='filmapp')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

filmapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Blog(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='images', blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.user.username} on {self.blog.title}'

    

filmapp/forms.py
from django import forms
from .models import Blog, Contact, Comment
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password1', 'password2']


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact  
        fields = ['name', 'email', 'message'] 

    def save(self, commit=True):
        instance = super().save(commit=False)
        # Perform any additional processing or validation here if needed
        if commit:
            instance.save()
        return instance

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'content', 'image']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

filmapp/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import Blog
from .forms import BlogForm, RegistrationForm, ContactForm, CommentForm
from django.core.paginator import Paginator
from django.db.models import Q
from .forms import CommentForm


def home(request):
    # Retrieve all blog posts
    all_blogs = Blog.objects.all().order_by('-created_at')

    # Set the number of blog posts to display per page
    blogs_per_page = 3

    # Create a Paginator instance
    paginator = Paginator(all_blogs, blogs_per_page)

    # Get the current page number from the request's GET parameters
    page_number = request.GET.get('page')

    # Get the Page object for the current page
    page = paginator.get_page(page_number)

    return render(request, 'filmapp/home.html', {'page': page})


def admin_posts(request):
    # Retrieve only admin blog posts
    admin_blogs = Blog.objects.filter(author__is_superuser=True).order_by('-created_at')

    # Set the number of blog posts to display per page
    blogs_per_page = 3

    # Create a Paginator instance
    paginator = Paginator(admin_blogs, blogs_per_page)

    # Get the current page number from the request's GET parameters
    page_number = request.GET.get('page')

    # Get the Page object for the current page
    page = paginator.get_page(page_number)

    return render(request, 'filmapp/admin_posts.html', {'page': page})



def guest_posts(request):
    # Retrieves only guests' blogs
    guest_posts = Blog.objects.filter(author__is_superuser=False).order_by('-created_at')

    blogs_per_page = 3

    paginator = Paginator(guest_posts, blogs_per_page)

    page_number = request.GET.get('page')

    page = paginator.get_page(page_number)

    return render(request, 'filmapp/guest_posts.html', {'page': page})


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():  
            form.save()  # Save the form data to the database
            return redirect("filmapp:login")  # Redirect to a success page or URL

    else:
        form = ContactForm()

    return render(request, 'filmapp/contact.html', {'form': form})


@login_required(login_url='filmapp:login')  # Add this decorator to require authentication.
def create_blog(request):
    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES)  # Include request.FILES for file uploads
        if form.is_valid():
            blog = form.save(commit=False)
            blog.author = request.user  # Assign the logged in user as the author
            blog.save()
            return redirect('filmapp:home')
    else:
        form = BlogForm()
    
    return render(request, 'filmapp/create_blog.html', {'form': form})


def register(request):
    form = RegistrationForm()
    password_errors = None

    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('filmapp:login')
        else:
            password_errors = form.errors.get('password1')

    return render(request, 'filmapp/auth/register.html', {'form': form})


def login_view(request):
    form = AuthenticationForm()
    password_errors = None

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('filmapp:home') 
        else:
            password_errors = form.errors.get('password')

    return render(request, 'filmapp/auth/login.html', {'form': form, 'password_errors': password_errors})


def logout_user(request):
    logout(request)
    return redirect('filmapp:login')


def blog_details(request, pk):
    blog = Blog.objects.get(pk=pk)
    return render(request, "filmapp/blog_details.html", {"blog": blog})


def search(request):
    query = request.GET.get('q')  # Get the search query from the request's GET parameters
    results = []

    if query:
        # Modify the search query to look for partial matches in both 'title' and 'content'
        results = Blog.objects.filter(Q(title__icontains=query) | Q(content__icontains=query))

    return render(request, 'filmapp/search_results.html', {'query': query, 'results': results})


def author_posts(request, author_id):
    author = get_object_or_404(User, id=author_id)  # Retrieve the author by their User ID
    author_posts = Blog.objects.filter(author=author)

    return render(request, 'filmapp/author_posts.html', {'author': author, 'author_posts': author_posts})


def blog_details(request, pk):
    blog = Blog.objects.get(pk=pk)
    comment_form = CommentForm()  # Create an instance of the CommentForm

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.blog = blog
            comment.user = request.user  # Assuming users are logged in when commenting
            comment.save()
            return redirect('filmapp:blog_details', pk=pk)

    return render(request, "filmapp/blog_details.html", {"blog": blog, "comment_form": comment_form})


def add_comment(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.blog = blog
            comment.user = request.user  # Assuming users are logged in when commenting
            comment.save()
            return redirect('filmapp:blog_details', pk=pk)
    else:
        return redirect('filmapp:blog_details', pk=pk)  # Redirect back to blog details if the form is invalid


def edit_blog(request, pk):
    blog = get_object_or_404(Blog, pk=pk)

    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES, instance=blog)
        if form.is_valid():
            form.save()
            return redirect('filmapp:blog_details', pk=pk)
    else:
        form = BlogForm(instance=blog)

    return render(request, 'filmapp/edit_blog.html', {'form': form, 'blog': blog})


def delete_blog(request, pk):
    blog = get_object_or_404(Blog, pk=pk)

    if request.method == 'POST':
        blog.delete()
        return redirect('filmapp:home')  # Redirect to the home page after deleting the blog

    return render(request, 'filmapp/delete_blog.html', {'blog': blog})

filmapp/templates/filmapp/admin_posts.html
{% extends "filmapp/base.html" %}

{% load custom_filters %}

{% block title %} FilmShift | {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <!-- Blogs Column -->
        <div class="col-md-10">
            <!-- Display blog posts in a grid with padding -->
            <div class="row">
                {% for blog in page %}
                <div class="col-md-4 mb-4">
                    <div class="blog-container">
                        <!-- Blog content -->
                        {% if blog.image %}
                        <img src="{{ blog.image.url }}" alt="{{ blog.title }}" class="blog-image">
                        {% endif %}
                        <a href="{% url 'filmapp:blog_details' pk=blog.id %}" class="blog-link"><h2 class="blog-title">{{ blog.title|upper }}</h2></a>
                        <p class="blog-meta">Posted on {{ blog.created_at|date:"F d, Y" }} | by <a href="{% url 'filmapp:author_posts' author_id=blog.author.id %}">{{ blog.author.username }}</a> </p>
                        {{ blog.content|slice_and_ellipsis:200 }}<a href="{% url 'filmapp:blog_details' pk=blog.id %}">[Read More]</a>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %} <!-- Open a new row after every 3 columns -->
                </div><div class="row">{% endif %}
                {% endfor %}
            </div>
            
            <!-- Pagination controls -->
            <div class="pagination mt-4">
                <span class="step-links">
                    {% if page.has_previous %}
                    <a href="?page=1" class="btn btn-primary btn-sm">&laquo; First</a>
                    <a href="?page={{ page.previous_page_number }}" class="btn btn-primary btn-sm">Previous</a>
                    {% endif %}

                    <span class="current-page">{{ page.number }}</span>

                    {% if page.has_next %}
                    <a href="?page={{ page.next_page_number }}" class="btn btn-primary btn-sm">Next</a>
                    <a href="?page={{ page.paginator.num_pages }}" class="btn btn-primary btn-sm">Last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
        
<!-- Sidebar Column -->
<div class="col-md-2 p-3" style="background-color: #f5ebeb; color: #888585; border-right: 1px solid #ccc; box-shadow: 2px 0px 4px rgba(0, 0, 0, 0.1);">
    <ul class="list-unstyled">
        {% if user.is_authenticated %}
        <!-- Display this if the user is logged in -->
        <li class="mb-2">
            <p>You are logged in as <strong><a href="{% url 'filmapp:author_posts' author_id=user.id %}">{{ user.username }}</a></strong></p>
        </li>
        <li class="mb-2">
            <a class="nav-link" href="{% url 'filmapp:logout_user' %}">
                <i class="fa fa-sign-out mr-2"></i> Log Out
            </a>
        </li>
        {% else %}
        <!-- Display this if the user is not logged in -->
        <li class="mb-2">
            <a class="nav-link" href="/login/">
                <i class="fa fa-sign-in mr-2"></i> Log In
            </a>
        </li>
        <li class="mb-2">
            <a class="nav-link" href="/register/">
                <i class="fa-solid fa-user-plus"></i> Register
            </a>
        </li>
        {% endif %}
    </ul>
</div>

<style>
        /* General styles */
        body {
            background-color: #f7f7f7;
            font-family: Arial, sans-serif;
        }
        .header {
            background-color: #292a2c;
            color: #ffffff;
            padding: 20px 0;
        }

        /* Main content styles */
        .main-content {
            background-color: #ffffff;
            box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
            padding: 20px;
            margin-top: 20px;
        }

        /* Sidebar styles */
        .sidebar {
            background-color: #f5ebeb;
            color: #888585;
            box-shadow: -4px 0px 8px rgba(0, 0, 0, 0.1);
            padding: 20px;
        }

        /* Blog container styles */
        .blog-container {
            padding: 20px;
            border: 1px solid #ddd;
            background-color: #fff;
            box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
        }

        .blog-image {
    max-width: 100%;
    height: 200px; /* Set a fixed height for all images */
    object-fit: cover;
    border-radius: 5px;
    display: block; /* Center-align the image horizontally */
    margin: 0 auto; /* Center-align the image horizontally */
        }

    .blog-title {
        font-size: 15px; /* Set the desired font size */
        font-weight: bold;
        color: #333; /* Adjust the color to your preference */
        text-align: center;

    }


</style>
{% endblock %}

filmapp/templates/filmapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <title>{% block title %}FilmShift | {% endblock %}</title>


    
    <style>
        .navbar {
            background-color: #292a2c; 
        }

        .navbar.sticky {
            position: sticky;
            top: 0;
            z-index: 1000;
        }

        /* Remove underlines from all links */
    a {
        text-decoration: none;
    }

    a:hover {
        color: #ff0000; 
    }

    .custom-font {
        font-family: 'Playfair Display';
    }

    </style>

</head>

<body>

<header class="header">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-4">
                <h1 class="logo" style="margin-bottom: -10px;">
                    <a href="/" style="text-decoration: none; color: goldenrod; font-family: 'Montserrat Bold', serif; font-size: 36px; font-weight: bold;">FILMSHIFT</a>
                </h1>
                <p class="description">A Blog for the Latest Movie and Trailer Reviews</p>
            </div>
            <div class="col-md-8 text-end">
                <form method="get" action="{% url 'filmapp:search' %}">
                    <input type="text" name="q" placeholder="Search...">
                    <button type="submit">Search</button>
                </form>            
            </div>
        </div>
    </div>
</header>


<nav class="navbar navbar-expand-lg navbar-dark sticky">
    <div class="container">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/"><i class="fa-solid fa-house-chimney-window"></i> Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/admin_posts"><i class="fa-solid fa-users-gear"></i></i> Admin Reviews</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/guest/"><i class="fa-solid fa-person-circle-check"></i> Guest Reviews</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/create/"><i class="fa fa-edit mr-2"></i> Create Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/contact/"><i class="fa fa-envelope mr-2"></i> Contact</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Your existing content container with max-width -->
<div class="container">
    {% block content %}
    <style>
        .max-width-container {
            max-width: 1200px; 
            margin: 0 auto; /* Center the content horizontally */
        
        }



    </style>
    <!-- Your content goes here -->
    {% endblock %}
</div>

</body>
</html>

filmapp/templates/filmapp/blog_details.html
{% extends "filmapp/base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-10 main-content">
            <div class="blog-container">
                {% if blog.image %}
                <div class="text-center">
                    <img src="{{ blog.image.url }}" alt="{{ blog.title }}" class="blog-image">
                </div>
                {% endif %}
                <h2 class="blog-title text-center">{{ blog.title|upper }}</h2>
                <p class="blog-meta text-center">
                    Posted on {{ blog.created_at|date:"F d, Y" }} | by
                    <a href="{% url 'filmapp:author_posts' author_id=blog.author.id %}">{{ blog.author.username }}</a>
                </p>
                {{ blog.content }}

                <!-- Add Edit Post link if user is authenticated and is the author -->
                {% if user.is_authenticated and user == blog.author %}
                <form method="get" action="{% url 'filmapp:edit_blog' pk=blog.pk %}">
                    <button type="submit" class="btn btn-primary">Modify Post</button>
                </form>
                {% endif %}            

                {% if user.is_authenticated and user == blog.author %}
                <form method="post" action="{% url 'filmapp:delete_blog' pk=blog.pk %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete Post</button>
                </form>
                {% endif %}            
            </div>
            

            <!-- Comments Section -->
            <div class="comments-section">
                <h3>Comments</h3>
                {% if blog.comments.all %}
                <div class="comment-list">
                    {% for comment in blog.comments.all %}
                    <div class="comment">
                        <div class="comment-header">
                            <strong><a href="{% url 'filmapp:author_posts' author_id=blog.author.id %}">{{ comment.user.username }}</a></strong> - {{ comment.created_at|date:"F d, Y" }}
                        </div>
                        <div class="comment-body">
                            {{ comment.text }}
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% else %}
                <p class="no-comments">No comments yet. Be the first to comment!</p>
                {% endif %}

                <!-- Comment Form -->
                {% if user.is_authenticated %}
                <div class="comment-form">
                    <h4>Add a Comment</h4>
                    <form method="post" action="{% url 'filmapp:add_comment' blog.id %}">
                        {% csrf_token %}
                        {{ comment_form.non_field_errors }}
                        <div class="form-group">
                            {{ comment_form.text.errors }}
                            {{ comment_form.text }}
                        </div>
                        <button type="submit">Add Comment</button>
                    </form>
                </div>
                {% else %}
                <p class="login-message">Please <a href="{% url 'filmapp:login' %}">login</a> to add comments.</p>
                {% endif %}
            </div>
        </div>



<!-- Sidebar Column -->
        <div class="col-md-2 p-3" style="background-color: #f5ebeb; color: #888585; border-right: 1px solid #ccc; box-shadow: 2px 0px 4px rgba(0, 0, 0, 0.1);">
            <ul class="list-unstyled">
                {% if user.is_authenticated %}
                <!-- Display this if the user is logged in -->
                <li class="mb-2">
                    <p>You are logged in as <strong>{{ user.username }}</strong></p>
                </li>
                <li class="mb-2">
                    <a class="nav-link" href="{% url 'filmapp:logout_user' %}">
                        <i class="fa fa-sign-out mr-2"></i> Log Out
                    </a>
                </li>
                {% else %}
                <!-- Display this if the user is not logged in -->
                <li class="mb-2">
                    <a class="nav-link" href="/login/">
                        <i class="fa fa-sign-in mr-2"></i> Log In
                    </a>
                </li>
                <li class="mb-2">
                    <a class="nav-link" href="/register/">
                        <i class="fa-solid fa-user-plus"></i> Register
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>

</div>

<style>
    /* General styles */
    body {
        background-color: #f7f7f7;
        font-family: Arial, sans-serif;
    }
    .header {
        background-color: #292a2c;
        color: #ffffff;
        padding: 20px 0;
    }

    /* Main content styles */
    .main-content {
        background-color: #ffffff;
        box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
        padding: 20px;
        margin-top: 20px;
    }

    /* Sidebar styles */
    .sidebar {
        background-color: #f5ebeb;
        color: #888585;
        box-shadow: -4px 0px 8px rgba(0, 0, 0, 0.1);
        padding: 20px;
    }

    /* Blog container styles */
    .blog-container {
        padding: 20px;
        border: 1px solid #ddd;
        background-color: #fff;
        box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);
        margin-bottom: 20px;
    }

    /* Blog image styles */
    .blog-image {
        max-width: 100%; /* Ensure the image scales to fit its container */
        height: auto; /* Maintain aspect ratio */
        object-fit: cover; /* Crop and center the image within its container */
        border-radius: 5px;
        width: 500px; /* Set a fixed width */
        height: 300px; /* Set a fixed height */
    }

    /* Styles for Comments Section */
    .comments-section {
        margin-top: 20px;
        border-top: 1px solid #ccc;
        padding-top: 20px;
    }

    .comment-list {
        margin-bottom: 20px;
    }

    .comment {
        border: 1px solid #eee;
        padding: 10px;
        margin-bottom: 15px;
    }

    .comment-header {
        font-weight: bold;
        margin-bottom: 5px;
    }

    .comment-body {
        margin-bottom: 10px;
    }

    .no-comments {
        font-style: italic;
        color: #888;
    }

    .comment-form {
        margin-top: 20px;
    }

    .login-message {
        font-style: italic;
        color: #888;
    }

    /* Comment form styles */
    form {
        margin-top: 20px;
    }

    input[type="submit"] {
        padding: 5px 10px;
        background-color: #007bff;
        color: #fff;
        border: none;
        cursor: pointer;
    }

    input[type="submit"]:hover {
        background-color: #0056b3;
    }

    button.btn-primary, button.btn-danger {
        margin-top: 10px; /* Adjust as needed */
        display: block; /* Show the button as a block element */
        width: 100%; /* Make button width fill its container */
    }

</style>
    
    {% endblock %}

filmapp/templates/filmapp/guest_posts.html
{% extends "filmapp/base.html" %}

{% load custom_filters %}

{% block title %} FilmShift | {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <!-- Blogs Column -->
        <div class="col-md-10">
            <!-- Display blog posts in a grid with padding -->
            <div class="row">
                {% for blog in page %}
                <div class="col-md-4 mb-4">
                    <div class="blog-container">
                        <!-- Blog content -->
                        {% if blog.image %}
                        <img src="{{ blog.image.url }}" alt="{{ blog.title }}" class="blog-image">
                        {% endif %}
                        <a href="{% url 'filmapp:blog_details' pk=blog.id %}" class="blog-link"><h2 class="blog-title">{{ blog.title|upper }}</h2></a>
                        <p class="blog-meta">Posted on {{ blog.created_at|date:"F d, Y" }} | by <a href="{% url 'filmapp:author_posts' author_id=blog.author.id %}"> {{ blog.author.username }} </a> </p>
                        {{ blog.content|slice_and_ellipsis:200 }}<a href="{% url 'filmapp:blog_details' pk=blog.id %}">[Read More]</a>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %} <!-- Open a new row after every 3 columns -->
                </div><div class="row">{% endif %}
                {% endfor %}
            </div>
            
            <!-- Pagination controls -->
            <div class="pagination mt-4">
                <span class="step-links">
                    {% if page.has_previous %}
                    <a href="?page=1" class="btn btn-primary btn-sm">&laquo; First</a>
                    <a href="?page={{ page.previous_page_number }}" class="btn btn-primary btn-sm">Previous</a>
                    {% endif %}

                    <span class="current-page">{{ page.number }}</span>

                    {% if page.has_next %}
                    <a href="?page={{ page.next_page_number }}" class="btn btn-primary btn-sm">Next</a>
                    <a href="?page={{ page.paginator.num_pages }}" class="btn btn-primary btn-sm">Last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
        
<!-- Sidebar Column -->
<div class="col-md-2 p-3" style="background-color: #f5ebeb; color: #888585; border-right: 1px solid #ccc; box-shadow: 2px 0px 4px rgba(0, 0, 0, 0.1);">
    <ul class="list-unstyled">
        {% if user.is_authenticated %}
        <!-- Display this if the user is logged in -->
        <li class="mb-2">
            <p>You are logged in as <strong><a href="{% url 'filmapp:author_posts' author_id=user.id %}">{{ user.username }}</a></strong></p>
        </li>
        <li class="mb-2">
            <a class="nav-link" href="{% url 'filmapp:logout_user' %}">
                <i class="fa fa-sign-out mr-2"></i> Log Out
            </a>
        </li>
        {% else %}
        <!-- Display this if the user is not logged in -->
        <li class="mb-2">
            <a class="nav-link" href="/login/">
                <i class="fa fa-sign-in mr-2"></i> Log In
            </a>
        </li>
        <li class="mb-2">
            <a class="nav-link" href="/register/">
                <i class="fa fa-edit mr-2"></i> Register
            </a>
        </li>
        {% endif %}
    </ul>
</div>
        
    </div>
</div>


    </div>
</div>

<style>
            /* General styles */
            body {
                background-color: #f7f7f7;
                font-family: Arial, sans-serif;
            }
            .header {
                background-color: #292a2c;
                color: #ffffff;
                padding: 20px 0;
            }

            /* Main content styles */
            .main-content {
                background-color: #ffffff;
                box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
                padding: 20px;
                margin-top: 20px;
            }

            /* Sidebar styles */
            .sidebar {
                background-color: #f5ebeb;
                color: #888585;
                box-shadow: -4px 0px 8px rgba(0, 0, 0, 0.1);
                padding: 20px;
            }

            /* Blog container styles */
            .blog-container {
                padding: 20px;
                border: 1px solid #ddd;
                background-color: #fff;
                box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);
                margin-bottom: 20px;
            }

            .blog-image {
        max-width: 100%;
        height: 200px; /* Set a fixed height for all images */
        object-fit: cover;
        border-radius: 5px;
        display: block; /* Center-align the image horizontally */
        margin: 0 auto; /* Center-align the image horizontally */
            }

        .blog-title {
            font-size: 15px; /* Adjust the font size as needed */
            font-weight: bold;
            color: #333; /* Adjust the color to your preference */
            text-align: center;
        }

        .pagination {
            margin-top: 20px; /* Adjust as needed */
            margin-bottom: 20px; /* Adjust as needed */
        }
</style>
{% endblock %}